// GENERATED by solana/scripts/setup-alts.ts. Do not edit by hand.
// Table 0: [program, canvas, vault, treasury, system, computeBudget]
// then tile PDAs row-major; tables 1..N continue tiles, 256/table.
export const ALT_TABLES = {
  "devnet": [
    "7dyrGEVyVgd6qLM4f28Pbb54tVyQv65BjVdjUp8P154z",
    "8GxSF9QSydg2czPMc5FG1raLbJt9eMeLSudAqq8tLvPR",
    "FKxyPAvoyBpKQG3rv72cF9cEhCTzqLrkotskViJQP5fB",
    "GK5MdnoDKtDRpn8LCRZ88J1gfsJEg4GLrvR67jEMhaZp",
    "AJQV4XYmoM1Ps9A2SNeN7azqhG9Qm62GkuS5LGbKunv4",
    "6jXuxNG3UUNaBLNsJwisS5RhXRRYTd5eesqBsihGW93A",
    "85FN9FB9FM7Wr5mfjastxq5a4hxapnXGVcdpMwa4W8Nq",
    "EfCUdxPBN7Yg2VZ1GFNFk845h9ANTEJb1MnScDAgXEo",
    "5QtA33JW8w4etQYfFb75w2xdazhRqexitH892x2eACYz",
    "5nbyU78r3H9wQ63ohJNqvndtfXSDwrWwe5H7vNMmifQ8"
  ]
} as const
export const ALT_FIXED_PREFIX = 6
export const ALT_TABLE_CAPACITY = 256
