import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'

import { AppLayout } from './components/AppLayout'
import CompetitionPage from './pages/CompetitionPage'
import EmbedPage from './pages/EmbedPage'
import FoundersPage from './pages/FoundersPage'
import HoldingPage from './pages/HoldingPage'
import HomePage from './pages/HomePage'
import OpsStatsPage from './pages/OpsStatsPage'
import SharePage from './pages/SharePage'
import TweetsPage from './pages/TweetsPage'
import './styles.css'

/**
 * Pre-launch holding-page mode. When `VITE_HOLDING_PAGE_MODE=true` at
 * build time, every route resolves to the holding page — no canvas, no
 * embed, no router-driven UX. Flip to false (or unset) to ship the
 * full app. Keeping this as one bundle (not a separate site) means
 * the Day-0 launch is one rebuild + one deploy, not a domain cutover.
 */
const HOLDING_MODE = import.meta.env.VITE_HOLDING_PAGE_MODE === 'true'

/**
 * Route map for the Tagwall frontend:
 *   /        main canvas view — canvas + paint controls + activity +
 *            leaderboard + inline stats cards. The Stats page was merged
 *            in here on 2026-04-23: no separate route, no nav menu.
 *   /pixel/  shareable permalink; opens canvas focused on a pixel.
 *   /embed   mirror-friendly minimal view without the layout chrome.
 */
export default function App() {
  if (HOLDING_MODE) return <HoldingPage />
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/embed" element={<EmbedPage />} />
        <Route element={<AppLayout />}>
          <Route path="/" element={<HomePage />} />
          <Route path="/pixel/:coord" element={<HomePage />} />
          {/* Legacy /stats links still resolve to the canvas page; the
              stats content now lives inline below the canvas. */}
          <Route path="/stats" element={<HomePage />} />
          <Route path="/share" element={<SharePage />} />
          {/* /founders — per-chain founder leaderboard + live "spots
              left" scarcity counter. Derived from on-chain paint order;
              no contract coupling. Linked from the top bar. */}
          <Route path="/founders" element={<FoundersPage />} />
          {/* /competition: live referral-contest page. Prize pool (80% of
              referred-paint volume, 5M PLS floor) + Top Referrers board,
              both read live from on-chain Painted events. */}
          <Route path="/competition" element={<CompetitionPage />} />
          {/* /tweets is an operator tool surfacing copy-ready tweets:
              cross-chain 7-day summary, per-chain weekly recaps, and
              individual notable-paint announcements. Public route
              (data is just chain-derived events) but intentionally
              unlinked from nav. Generated by bots/tweets/ ->
              web/public/{queue,summary}.json. */}
          <Route path="/tweets" element={<TweetsPage />} />
          {/* /ops: operator cross-chain stats dashboard. Live all-time
              on-chain reads (stampCount / floor / treasury) + the tweets
              bot's windowed summary.json (unique painters, Gini, daily
              trend) + viewer-chain coverage. Public but unlinked from nav,
              same posture as /tweets. */}
          <Route path="/ops" element={<OpsStatsPage />} />
          {/* Backward-compat: the page used to live at /queue. Keep
              the redirect so any operator bookmarks still resolve. */}
          <Route path="/queue" element={<Navigate to="/tweets" replace />} />
          {/* Catch-all: any unknown path lands on the canvas rather than a
              blank screen. A mistyped URL or a stale deep link should never
              dead-end. Kept last so it only matches when nothing else did. */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Route>
      </Routes>
    </BrowserRouter>
  )
}
